### ISSUE TITLE
Cool.io::TCPServer continues to receive data even if its close method is called

### ISSUE THREAD

**Issue by abicky** [socketry/cool.io#61] opened 2017-10-22 13:49 UTC
I expect `Cool.io::TCPServer` to stop receiving data after `Cool.io::TCPServer#close` is called, but it continues to receive data. Is this behavior expected?

Here is a reproducible code:

```ruby
require 'socket'
require 'cool.io'

HOST = '127.0.0.1'
PORT = 1234

class ServerConnection < Coolio::TCPSocket
  def on_read(data)
    puts "received: #{data}"
  end
end

event_loop = Coolio::Loop.new
server = Cool.io::TCPServer.new(HOST, PORT, ServerConnection)
server.attach(event_loop)

server_thr = Thread.new { event_loop.run }
sock = TCPSocket.new(HOST, PORT)

puts "cool.io version: #{Coolio::VERSION}"

puts 'send a message'
sock.send "message", 0
sleep 1

server.close
puts 'server stopped'
sleep 1

puts 'send a message'
sock.send "message", 0
sleep 1

puts 'done'
```

Output

```
% docker run --rm -v $PWD/coolio_example.rb:/coolio_example.rb ruby:2.4.2 bash -c 'gem install cool.io && ruby /coolio_example.rb'
Building native extensions.  This could take a while...
Successfully installed cool.io-1.5.1
1 gem installed
cool.io version: 1.5.1
send a message
received: message
server stopped
send a message
received: message
done
```

**Comment by repeatedly** [comment] 2017-10-24 01:59
You need to call `Loop#stop` before `server.close`.

**Comment by ganmacs** [comment] 2019-10-03 06:01
I think this is expected behavior.
What Cool.io::TCPServer#close does is just closing a listening socket[*](https://github.com/tarcieri/cool.io/blob/0fd3fd1d8e8d81e24f79f809979367abc3f52b92/lib/cool.io/listener.rb#L29-L32), not closing the accepted socket. the method is similar to `TcpServer#close`.

So here is the correct code to shutdown coolio.

```rb
require 'socket'
require  'cool.io'

HOST = '127.0.0.1'
PORT = 1234

class ServerConnection < Coolio::TCPSocket
  def on_read(data)
    puts "received: #{data}"
  end
end

event_loop = Coolio::Loop.new
conns = []
server = Cool.io::TCPServer.new(HOST, PORT, ServerConnection) do |conn|
  conns << conn
end
server.attach(event_loop)

server_thr = Thread.new { event_loop.run }
sock = TCPSocket.new(HOST, PORT)

puts "cool.io version: #{Coolio::VERSION}"

puts 'send a message'
sock.send "message", 0
sleep 1

server.close
conns.each do |c|
  c.close
end
puts 'server stopped'
sleep 1

puts 'send a message'
sock.send "message", 0
sleep 1

puts 'done'
```

```
$ docker run --rm -v $PWD/coolio_example.rb:/coolio_example.rb ruby:2.6 bash -c 'gem install cool.io && ruby /coolio_example.rb'
Building native extensions. This could take a while...
Successfully installed cool.io-1.5.4
1 gem installed
cool.io version: 1.5.4
send a message
received: message
server stopped
send a message
done
```

We can find another problem here.
Calling second `sock.send "message", 0` succeeded even if the accepted socket was already closed on the server-side.
it seems to be related to https://github.com/fluent/fluentd/issues/1985 .

**Comment by ioquatix** [comment] 2023-08-02 10:56
It sounds wrong to me, but please consider making a PR, as I don't think anyone is invested in maintaining this code base.

**Closed by ioquatix** 2023-08-02 10:56 UTC
